{{- range $item := list (dict "name" "keycloak-db" "path" "database") (dict "name" "keycloak-bootstrap" "path" "bootstrap") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}
spec:
  refreshInterval: 1h
  secretStoreRef: {name: keycloak-vault, kind: SecretStore}
  target: {name: {{ $item.name }}, creationPolicy: Owner, deletionPolicy: Retain}
  data:
    - secretKey: username
      remoteRef: {key: "cnp/keycloak/{{ $.Values.instanceKey }}/{{ $item.path }}", property: username}
    - secretKey: password
      remoteRef: {key: "cnp/keycloak/{{ $.Values.instanceKey }}/{{ $item.path }}", property: password}
{{- end }}
