apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: keycloak-vault
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: secret
      version: v2
      auth:
        tokenSecretRef: {name: keycloak-eso-token, key: token}
