apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    {{- include "cnp-keycloak.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.postgresql.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize | quote }}
