"""Generate the Dockerfile / Helm chart missing from a registered repo (never overwrites).

Python (FastAPI/Flask) gets a working Dockerfile; anything else a skeleton whose build fails on purpose.
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field

import yaml
from shared.models import ScaffoldingParams

from backend.ci.templates import _FRAMEWORK_ALIASES
from backend.core.config import settings
from backend.gitlab.client import GitLabClient
from backend.services.scaffolding_service import build_chart_yaml, build_values_yaml

logger = logging.getLogger(__name__)

APP_PORT = 8000

# Framework key → CNP template repo whose chart/ is reused. Charts are
# framework-agnostic apart from probes; 'generic' falls back to python-fastapi.
_CHART_TEMPLATES = {"python": "python-fastapi", "nodejs": "node-express", "go": "go"}
_DEFAULT_CHART_TEMPLATE = "python-fastapi"
_GENERATED_CHART_FILES = {"chart/values.yaml", "chart/Chart.yaml"}

# Candidate modules holding the ASGI/WSGI application object, in lookup order.
_PYTHON_ENTRYPOINTS = ("main.py", "app.py", "src/main.py", "src/app.py", "app/main.py")
_APP_OBJECT_RE = re.compile(r"^(\w+)\s*=\s*(?:\w+\.)?(FastAPI|Flask)\(", re.MULTILINE)


@dataclass
class BuildFiles:
    files: dict[str, str] = field(default_factory=dict)
    todos: list[str] = field(default_factory=list)


def generate_missing_build_files(
    client: GitLabClient,
    project_path: str,
    app_slug: str,
    framework: str,
    owner: str = "unknown",
    ref: str = "main",
) -> BuildFiles:
    """Return the Dockerfile / chart files missing from the repo root at `ref`."""
    framework = _FRAMEWORK_ALIASES.get(framework, framework)
    root = {item["name"] for item in client.list_tree(project_path, path="", ref=ref)}
    result = BuildFiles()

    if "Dockerfile" not in root:
        if framework == "python":
            dockerfile = _python_dockerfile(client, project_path, ref, root)
        else:
            dockerfile = None
        if dockerfile is None:
            dockerfile = _skeleton_dockerfile(framework)
            result.todos.append(
                "`Dockerfile` : CNP n'a pas pu déduire comment construire et démarrer l'application. "
                "Complétez-le — le build échoue volontairement tant que ce n'est pas fait."
            )
        result.files["Dockerfile"] = dockerfile

    if "chart" not in root:
        result.files.update(_chart_files(client, project_path, app_slug, framework, owner))

    return result


def _python_dockerfile(client: GitLabClient, project_path: str, ref: str, root: set[str]) -> str | None:
    entrypoint = _find_python_app(client, project_path, ref, root)
    if entrypoint is None:
        return None
    module, variable, kind = entrypoint

    if "requirements.txt" in root:
        install = [
            "COPY requirements.txt .",
            "RUN pip install --no-cache-dir -r requirements.txt",
            "COPY . .",
        ]
    elif "pyproject.toml" in root or "setup.py" in root:
        install = ["COPY . .", "RUN pip install --no-cache-dir ."]
    elif "Pipfile" in root:
        deploy = " --deploy" if "Pipfile.lock" in root else ""
        install = [
            "COPY . .",
            f"RUN pip install --no-cache-dir pipenv && pipenv install --system{deploy}",
        ]
    else:
        install = ["COPY . ."]

    if kind == "FastAPI":
        server = "RUN pip install --no-cache-dir uvicorn"
        cmd = f'CMD ["uvicorn", "{module}:{variable}", "--host", "0.0.0.0", "--port", "{APP_PORT}"]'
    else:
        server = "RUN pip install --no-cache-dir gunicorn"
        cmd = f'CMD ["gunicorn", "--bind", "0.0.0.0:{APP_PORT}", "{module}:{variable}"]'

    lines = [
        "# Generated by CNP — review before merging.",
        "FROM python:3.12-slim",
        "",
        "ENV PYTHONDONTWRITEBYTECODE=1 \\",
        "    PYTHONUNBUFFERED=1",
        "",
        "WORKDIR /app",
        "",
        server,
        "",
        *install,
        "",
        "RUN useradd --create-home appuser && chown -R appuser:appuser /app",
        "USER appuser",
        "",
        f"EXPOSE {APP_PORT}",
        "",
        cmd,
    ]
    return "\n".join(lines) + "\n"


def _find_python_app(
    client: GitLabClient, project_path: str, ref: str, root: set[str]
) -> tuple[str, str, str] | None:
    """Return (module, variable, 'FastAPI'|'Flask') for the first app object found."""
    for path in _PYTHON_ENTRYPOINTS:
        if path.split("/", 1)[0] not in root:
            continue
        try:
            source = client.read_file(project_path, path, ref=ref)
        except Exception:
            continue
        match = _APP_OBJECT_RE.search(source)
        if match:
            module = path.removesuffix(".py").replace("/", ".")
            return module, match.group(1), match.group(2)
    return None


def _skeleton_dockerfile(framework: str) -> str:
    return f"""\
# Generated by CNP — TODO: CNP could not infer how to build/start this app ({framework}).
# The build fails on purpose until the RUN line below is replaced. Listen on 0.0.0.0:{APP_PORT}.
FROM debian:bookworm-slim

WORKDIR /app

COPY . .

# TODO: replace this line with your build steps.
RUN echo "CNP: this Dockerfile is a skeleton — add build steps and a CMD, then remove this line." >&2 && exit 1

EXPOSE {APP_PORT}

# TODO: set the start command.
CMD ["false"]
"""


def _chart_files(
    client: GitLabClient, project_path: str, app_slug: str, framework: str, owner: str
) -> dict[str, str]:
    if not settings.GITLAB_TEMPLATES_NAMESPACE:
        raise RuntimeError("GITLAB_TEMPLATES_NAMESPACE is not configured")
    template = _CHART_TEMPLATES.get(framework, _DEFAULT_CHART_TEMPLATE)
    template_path = f"{settings.GITLAB_TEMPLATES_NAMESPACE}/{template}"

    files: dict[str, str] = {}
    for item in client.list_tree_recursive(template_path):
        path = item["path"]
        if item["type"] != "blob" or not path.startswith("chart/") or path in _GENERATED_CHART_FILES:
            continue
        files[path] = client.read_file(template_path, path)

    registry_host = settings.GITLAB_REGISTRY_URL.rstrip("/")
    params = ScaffoldingParams(
        port=APP_PORT,
        # Must match $CI_REGISTRY_IMAGE, where docker-build pushes (always lowercase).
        image_repository=f"{registry_host}/{project_path.lower()}",
    )
    values = yaml.safe_load(build_values_yaml(app_slug, "", params, gitlab_group_path=owner))
    # Imported apps rarely expose /health: probe the port instead (see template deployment.yaml).
    values["probes"] = {"type": "tcp"}
    files["chart/values.yaml"] = yaml.safe_dump(values, default_flow_style=False, sort_keys=False)
    files["chart/Chart.yaml"] = build_chart_yaml(app_slug)
    return files
