from backend.core.config import settings

_ALLOWED_FRAMEWORKS = {"python", "generic"}

# Maps template/framework names to their CI framework key
_FRAMEWORK_ALIASES = {
    "python-fastapi": "python",
    "python-flask": "python",
}


def _yaml_escape(value: str) -> str:
    """Escape a string for insertion in a YAML double-quoted scalar."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")


def _ci_templates_project() -> str:
    if settings.GITLAB_CI_PROJECT:
        return settings.GITLAB_CI_PROJECT
    ns = settings.GITLAB_BOT_NAMESPACE or "cnp"
    return f"{ns}/cnp-ci-modules"

def generate_gitlab_ci(app_name: str, app_id: int, framework: str) -> str:
    """Generate the minimal .gitlab-ci.yml to inject into a user repo."""
    framework = _FRAMEWORK_ALIASES.get(framework, framework)
    if framework not in _ALLOWED_FRAMEWORKS:
        raise ValueError(f"Unknown framework '{framework}' — allowed: {_ALLOWED_FRAMEWORKS}")

    templates_project = _ci_templates_project()
    safe_name = _yaml_escape(app_name)
    gitops_repo = _yaml_escape(settings.GITOPS_REPO_URL)
    gitops_app_path = f"apps/{_yaml_escape(app_name)}"

    lines = [
        "# Auto-generated by CNP — do not edit manually\n",
        "variables:\n",
        f'  CNP_APP_NAME: "{safe_name}"\n',
        f'  CNP_APP_ID: "{app_id}"\n',
        f'  CNP_GITOPS_REPO: "{gitops_repo}"\n',
        f'  CNP_GITOPS_APP_PATH: "{gitops_app_path}"\n',
        "\n",
        "include:\n",
        f"  - project: '{templates_project}'\n",
        "    ref: main\n",
        "    file: '/base/pipeline.yml'\n",
    ]
    if framework != "generic":
        lines += [
            f"  - project: '{templates_project}'\n",
            "    ref: main\n",
            f"    file: '/frameworks/{framework}.yml'\n",
        ]
    return "".join(lines)

