from backend.core.config import settings

_ALLOWED_FRAMEWORKS = {"python", "generic"}


def _yaml_escape(value: str) -> str:
    """Escape a string for insertion in a YAML double-quoted scalar."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")


def generate_gitlab_ci(app_name: str, app_id: int, framework: str) -> str:
    """Generate the .gitlab-ci.yml to inject into a user repo.

    The generated pipeline implements a GitOps workflow:
    - Push on main   → build image tagged :main-<sha>    → update cnp-gitops staging values
    - Git tag pushed → build image tagged :<tag>          → update cnp-gitops prod values

    The CI pipeline uses CNP_BOT_TOKEN (a GitLab CI/CD variable, never stored in Git)
    to authenticate against the cnp-gitops repository.
    """
    if framework not in _ALLOWED_FRAMEWORKS:
        raise ValueError(f"Unknown framework '{framework}' — allowed: {_ALLOWED_FRAMEWORKS}")

    safe_name = _yaml_escape(app_name)
    gitops_repo = _yaml_escape(settings.GITOPS_REPO_URL)
    # Convention: the app's folder in cnp-gitops mirrors the app_name.
    gitops_app_path = f"apps/{_yaml_escape(app_name)}"

    # Build the docker build script snippet, framework-specific if needed
    framework_build_lines = ""
    if framework == "python":
        framework_build_lines = (
            "    # Python: ensure dependencies are resolved before build\n"
            "    - echo 'Python project detected — standard Dockerfile build applies'\n"
        )

    return f"""\
# Auto-generated by CNP — do not edit manually
# Workflow: push main → staging | git tag → prod

variables:
  CNP_APP_NAME: "{safe_name}"
  CNP_APP_ID: "{app_id}"
  CNP_GITOPS_REPO: "{gitops_repo}"
  CNP_GITOPS_APP_PATH: "{gitops_app_path}"
  REGISTRY: "$CI_REGISTRY"
  IMAGE_NAME: "$REGISTRY/$CI_PROJECT_PATH"

stages:
  - build
  - deploy

# ─── Build ────────────────────────────────────────────────────────────────────

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$REGISTRY"
  script:
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_SHA" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHA"
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag "$IMAGE_NAME:$CI_COMMIT_SHA" "$IMAGE_NAME:$CI_COMMIT_TAG"
        docker push "$IMAGE_NAME:$CI_COMMIT_TAG"
      else
        docker tag "$IMAGE_NAME:$CI_COMMIT_SHA" "$IMAGE_NAME:main-$CI_COMMIT_SHORT_SHA"
        docker push "$IMAGE_NAME:main-$CI_COMMIT_SHORT_SHA"
      fi

# ─── Deploy staging (push on main) ───────────────────────────────────────────

deploy-staging:
  stage: deploy
  image: alpine/git:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - git clone "https://cnp-bot:$CNP_BOT_TOKEN@${{CNP_GITOPS_REPO#https://}}" cnp-gitops
    - cd cnp-gitops
    - |
      sed -i "s|^  tag:.*|  tag: main-$CI_COMMIT_SHORT_SHA|" "$CNP_GITOPS_APP_PATH/values-staging.yaml"
    - git config user.email "cnp-bot@cnp.local"
    - git config user.name "CNP Bot"
    - git add "$CNP_GITOPS_APP_PATH/values-staging.yaml"
    - git commit -m "chore(gitops): $CNP_APP_NAME staging → main-$CI_COMMIT_SHORT_SHA [skip ci]"
    - git push

# ─── Deploy prod (git tag) ────────────────────────────────────────────────────

deploy-prod:
  stage: deploy
  image: alpine/git:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - git clone "https://cnp-bot:$CNP_BOT_TOKEN@${{CNP_GITOPS_REPO#https://}}" cnp-gitops
    - cd cnp-gitops
    - |
      sed -i "s|^  tag:.*|  tag: $CI_COMMIT_TAG|" "$CNP_GITOPS_APP_PATH/values-prod.yaml"
    - git config user.email "cnp-bot@cnp.local"
    - git config user.name "CNP Bot"
    - git add "$CNP_GITOPS_APP_PATH/values-prod.yaml"
    - git commit -m "chore(gitops): $CNP_APP_NAME prod → $CI_COMMIT_TAG [skip ci]"
    - git push
"""

