"""cluster_monitoring_urls

Revision ID: 4f49148a68c3
Revises: 2b2a5bb9d2f7
Create Date: 2026-06-23 03:17:23.635743

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4f49148a68c3'
down_revision = '2b2a5bb9d2f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_app_members_id'), 'app_members', ['id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_app_id'), table_name='audit_logs')
    op.add_column('cluster_connections', sa.Column('prometheus_url', sa.String(), nullable=True))
    op.add_column('cluster_connections', sa.Column('loki_url', sa.String(), nullable=True))
    op.add_column('cluster_connections', sa.Column('argocd_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.create_index(op.f('ix_gitlab_group_members_id'), 'gitlab_group_members', ['id'], unique=False)
    op.drop_constraint(op.f('uq_users_gitlab_user_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_gitlab_user_id'), table_name='users')
    op.create_index(op.f('ix_users_gitlab_user_id'), 'users', ['gitlab_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_gitlab_user_id'), table_name='users')
    op.create_index(op.f('ix_users_gitlab_user_id'), 'users', ['gitlab_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_gitlab_user_id'), 'users', ['gitlab_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_gitlab_group_members_id'), table_name='gitlab_group_members')
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.drop_column('cluster_connections', 'argocd_url')
    op.drop_column('cluster_connections', 'loki_url')
    op.drop_column('cluster_connections', 'prometheus_url')
    op.create_index(op.f('ix_audit_logs_app_id'), 'audit_logs', ['app_id'], unique=False)
    op.drop_index(op.f('ix_app_members_id'), table_name='app_members')
    # ### end Alembic commands ###
